failed attempt at using integrated gradients with GBM
Error: element 0 of tensors does not require grad and does not have a grad_fn

Seems like the hummingbird converted model does not support tracking gradients